FeedBunch-app/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'
require 'sidekiq-cron'

Rails.application.routes.draw do

  # Custom dynamic error pages
  %w( 404 422 500 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

  devise_for :users, skip: [:sessions, :passwords, :registrations, :confirmations, :unlocks]

  # Customize login, logout etc routes instead of the Devise defaults.
  # See this[https://github.com/plataformatec/devise/wiki/How-To:-Change-the-default-sign_in-and-sign_out-routes].
  devise_scope :user do
    # sessions
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session,via: Devise.mappings[:user].sign_out_via

    # passwords
    get '/password/new' => 'devise/passwords#new', as: :new_user_password
    post '/password/new' => 'devise/passwords#create', as: :user_password
    get '/password/edit' => 'devise/passwords#edit', as: :edit_user_password
    put '/password/edit' => 'devise/passwords#update'

    # registrations
    get '/signup' => 'devise/registrations#new', as: :new_user_registration
    post '/signup' => 'feedbunch_auth/registrations#create', as: :user_registration
    get '/profile' => 'devise/registrations#edit', as: :edit_user_registration
    put '/profile' => 'devise/registrations#update'
    delete '/profile' => 'feedbunch_auth/registrations#destroy', as: :delete_user_registration

    # confirmations
    get '/resend_confirmation' => 'devise/confirmations#new', as: :new_user_confirmation
    post '/resend_confirmation' => 'devise/confirmations#create', as: :user_confirmation
    get '/confirmation' => 'devise/confirmations#show'

    # unlocks
    get '/unlock' => 'devise/unlocks#new', as: :new_user_unlock
    post '/unlock' => 'devise/unlocks#create', as: :user_unlock
    get '/unlock_account' => 'devise/unlocks#show'
  end

  # Redirect authenticated users that access the root URL to '/read'
  authenticated :user do
    get '/'  => redirect('/read')
  end

  # Static pages served with High_voltage gem
  root to: 'high_voltage/pages#show', id: 'index'
  get '/signup-success' => 'high_voltage/pages#show', id: 'signup-success', as: :signup_success

  # Main app page
  get '/read' => 'read#index', as: :read

  namespace :api do

    # Change entries state
    match '/entries/update' => 'entries#update', via: [:patch, :put], as: 'entries_update'

    # Resourceful routes for feeds
    resources :feeds, only: [:index, :show, :create, :update, :destroy] do
      resources :entries, only: [:index]
    end

    # Resourceful routes for folders
    resources :folders, only: [:index, :show, :update, :create] do
      resources :entries, only: [:index]
      resources :feeds, only: [:index]
    end

    # Resourceful routes for subscriptions import process state
    resource :opml_imports, only: [:show, :create, :update]

    # Resourceful routes for subscriptions export process state
    resource :opml_exports, only: [:show, :create, :update]

    # Download OPML export file
    match '/opml_exports/download' => 'opml_exports#download', via: [:get], as: 'opml_exports_download'

    # Resourceful routes for user config
    resource :user_config, only: [:show, :update]

    # Resourceful routes for user data
    resource :user_data, only: [:show]

    # Resourceful routes for refresh_feed_job_states
    resources :refresh_feed_job_states, only: [:index, :show, :destroy]

    # Resourceful routes for subscribe_job_states
    resources :subscribe_job_states, only: [:index, :show, :destroy]

    # Resourceful routes for application tours i18n strings.
    match '/tours/main' => 'tours#show_main', via: [:get], as: 'tours_show_main'
    match '/tours/mobile' => 'tours#show_mobile', via: [:get], as: 'tours_show_mobile'
    match '/tours/feed' => 'tours#show_feed', via: [:get], as: 'tours_show_feed'
    match '/tours/entry' => 'tours#show_entry', via: [:get], as: 'tours_show_entry'
    match '/tours/kb_shortcuts' => 'tours#show_kb_shortcuts', via: [:get], as: 'tours_show_kb_shortcuts'
  end

  # Restrict access to Sidekiq web ui to admin users only
  constraints CanAccessSidekiq do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Redmon is only accessible for admins
  constraints CanAccessRedmon do
    mount Redmon::App => '/redmon'
  end

  # ActiveAdmin is only accessible for admins
  constraints CanAccessActiveAdmin do
    # ActiveAdmin will be accessible in the /admin path
    ActiveAdmin.routes self
  end

  # PgHero is only accessible for admins
  constraints CanAccessPgHero do
    mount PgHero::Engine, at: 'pghero'
  end
end

FeedBunch-app/app/views/layouts/navbar/_feeds_menu.html.erb
<li id="feed-dropdown"
    class="dropdown"
    ng-show="show_feed_buttons"
    data-toggle="tooltip" data-placement="right"
    title="<%= t 'layouts.navbar.feed_menu_button_tooltip' %>">

  <a id="feeds-management"
     class="dropdown-toggle"
     ng-click="toggle_feeds_menu()">
    <i class="fa fa-rss fa-fw"></i> <%= t 'layouts.navbar.feed_menu_button' %>
    <i class="fa fa-caret-down fa-fw"></i>
  </a>

  <ul class="dropdown-menu text-left">

    <li>
      <a id="add-subscription"
         data-target="#subscribe-feed-popup"
         data-toggle="modal">
        <i class="fa fa-plus fa-fw"></i> <%= t 'layouts.navbar.subscribe_button' %>
      </a>
    </li>

    <li ng-show="current_feed">
      <a id="refresh-feed"
         ng-click="refresh_feed()">
        <i class="fa fa-repeat fa-fw"></i> <%= t 'layouts.navbar.refresh_button' %>
      </a>
    </li>

    <li ng-show="current_feed">
      <a id="unsubscribe-feed"
         data-toggle="modal"
         data-target="#unsubscribe-feed-popup">
        <i class="fa fa-times fa-fw"></i> <%= t 'layouts.navbar.unsubscribe_button' %>
      </a>
    </li>

  </ul>
</li>

FeedBunch-app/app/views/layouts/navbar/_folders_menu.html.erb
<li id="folder-management-dropdown"
    class="dropdown"
    ng-show="current_feed"
    data-toggle="tooltip" data-placement="right"
    title="<%= t 'layouts.navbar.folder_button_tooltip' %>">

  <a id="folder-management"
     class="dropdown-toggle"
     ng-click="toggle_folders_menu()">
    <i class="fa fa-folder-open fa-fw"></i> <%= t 'layouts.navbar.folder_button' %>
    <i class="fa fa-caret-down fa-fw"></i>
  </a>

  <ul id="folder-dropdown-content" class="dropdown-menu text-left">

    <li ng-repeat="folder in folders | orderBy:'title'">
      <a data-folder-id="{{folder.id}}"
         ng-click="move_to_folder(folder)">
        <i class="fa fa-check fa-fw" ng-show="get_current_feed().folder_id==folder.id"></i>
        <i class="fa fa-fw" ng-hide="get_current_feed().folder_id==folder.id"></i>
        <span class="dropdown-folder-title">{{folder.title}}</span>
      </a>
    </li>

    <li class="divider" ng-show="folders.length > 0"></li>

    <li>
      <a data-folder-id="new"
         data-toggle="modal"
         data-target="#new-folder-popup">
        <i class="fa fa-plus fa-fw text-muted"></i>
        <span class="dropdown-folder-title"><%= t 'layouts.navbar.folder_new' %></span>
      </a>
    </li>

    <li>
      <a data-folder-id="none"
         ng-click="remove_from_folder()">
        <i class="fa fa-ban fa-fw text-muted" ng-hide="get_current_feed().folder_id=='none'"></i>
        <i class="fa fa-check fa-fw" ng-show="get_current_feed().folder_id=='none'"></i>
        <span class="dropdown-folder-title"><%= t 'layouts.navbar.folder_none' %></span>
      </a>
    </li>

  </ul>
</li>

FeedBunch-app/app/views/layouts/navbar/_navbar.html.erb
<% cache "navbar-#{I18n.locale}" do %>

  <div id="navbar" class="navbar navbar-default navbar-fixed-top">

    <div class="navbar-header">

      <%= render 'layouts/navbar/xs_menu_button' %>

      <%= render 'layouts/navbar/xs_sidebar_toggle_button' %>

      <%= link_to read_path, class: 'navbar-brand', id: 'feedbunch-brand' do %>
        <%= image_tag asset_path('logo18x18.png'), alt: 'FeedBunch' %>
        FeedBunch
      <% end %>

    </div>

    <div class="collapse navbar-collapse">

      <ul class="nav navbar-nav" ng-cloak>

        <%= render 'layouts/navbar/show_hide_read_button' %>

        <%= render 'layouts/navbar/feeds_menu' %>

        <%= render 'layouts/navbar/read_all_button' %>

        <%= render 'layouts/navbar/folders_menu' %>

      </ul>

<% end %>

      <%= render 'layouts/navbar/user_menu' %>

    </div>

  </div>

FeedBunch-app/app/views/layouts/navbar/_read_all_button.html.erb
<li id="read-all-button-wrapper"
    ng-show="show_feed_buttons && (current_feed || current_folder)"
    data-toggle="tooltip" data-placement="right"
    title="<%= t 'layouts.navbar.read_all_button_tooltip' %>">
  <a id="read-all-button" ng-click="mark_all_read()">
    <i class="fa fa-check-square-o fa-fw"></i> <%= t 'layouts.navbar.read_all_button' %>
  </a>
</li>

FeedBunch-app/app/views/layouts/navbar/_show_hide_read_button.html.erb
<li id="show-hide-read-button">

  <a id="show-read"
     ng-show="show_feed_buttons && !show_read"
     data-toggle="tooltip"
     data-placement="right"
     data-container="body"
     title="<%= t 'layouts.navbar.show_read_button_tooltip' %>"
     ng-click="show_read_feeds_entries()">
    <i class="fa fa-eye fa-fw"></i> <%= t 'layouts.navbar.show_read_button' %>
  </a>

  <a id="hide-read"
     ng-show="show_feed_buttons && show_read"
     data-toggle="tooltip"
     data-placement="right"
     data-container="body"
     title="<%= t 'layouts.navbar.hide_read_button_tooltip' %>"
     ng-click="hide_read_feeds_entries()">
    <i class="fa fa-eye-slash fa-fw"></i> <%= t 'layouts.navbar.hide_read_button' %>
  </a>
</li>

FeedBunch-app/app/views/layouts/navbar/_user_menu.html.erb
<ul class="nav navbar-nav navbar-right">

  <li id="user-dropdown"
      class="dropdown">
    <a id="user-management"
       class="dropdown-toggle"
       ng-click="toggle_user_menu()">
      <i class="fa fa-user fa-fw"></i>
      <span id="user-name"><%= current_user.name %></span>
      <i class="fa fa-caret-down fa-fw"></i>
    </a>

<%#= Cache different versions of the user menu for admin and non-admin users
 (admin users have more options available).
 Also cache different versions for the read page (without "read feeds" option) and for other pages
 (with "read feeds" menu option).%>
<% cache "user_menu-#{current_user.admin ? 'admin':'noadmin'}-#{(current_page? '/read') ? 'read_page':'no_read_page'}-#{I18n.locale}" do %>

      <ul class="dropdown-menu">

        <% if can? :manage, ActiveAdmin %>
          <li>
            <%= link_to '/admin', target: '_blank', rel: 'noopener noreferrer' do %>
              <i class="fa fa-wrench fa-fw"></i>
              <%= t 'layouts.navbar.admin' %>
            <% end %>
          </li>
        <% end %>

        <% if can? :manage, PgHero %>
          <li>
            <%= link_to '/pghero', target: '_blank', rel: 'noopener noreferrer' do %>
              <i class="fa fa-database fa-fw"></i>
              <%= t 'layouts.navbar.db_stats' %>
            <% end %>
          </li>
        <% end %>

        <% if can? :manage, Redmon %>
          <li>
            <%= link_to '/redmon', target: '_blank', rel: 'noopener noreferrer' do %>
              <i class="fa fa-area-chart fa-fw"></i>
              <%= t 'layouts.navbar.cache_stats' %>
            <% end %>
          </li>
        <% end %>

        <% if can? :manage, Sidekiq %>
          <li>
            <%= link_to sidekiq_web_path, target: '_blank', rel: 'noopener noreferrer' do %>
              <i class="fa fa-code-fork fa-fw"></i>
              <%= t 'layouts.navbar.background_jobs' %>
            <% end %>
          </li>
        <% end %>

        <% if !current_page? '/read' %>
          <li>
            <%=  link_to read_path, id: 'read_feeds' do %>
              <i class="fa fa-rss fa-fw"></i>
              <%= t 'layouts.navbar.read_feeds' %>
            <% end %>
          </li>
        <% end %>

        <li>
          <%=  link_to edit_user_registration_path, id: 'my_account' do %>
            <i class="fa fa-gear fa-fw"></i>
            <%= t 'layouts.navbar.my_account' %>
          <% end %>
        </li>

        <li>
          <a id="help-kb-shortcuts"
             data-toggle="modal"
             data-target="#help-kb-shortcuts-popup">
            <i class="fa fa-keyboard-o fa-fw"></i>
            <%= t 'layouts.navbar.kb_shortcuts' %>
          </a>
        </li>

        <li>
          <a id="help"
             data-toggle="modal"
             data-target="#help-feedback-popup">
            <i class="fa fa-question fa-fw"></i>
            <%= t 'layouts.navbar.help' %>
          </a>
        </li>

        <li>
          <%= link_to destroy_user_session_path, :method => :delete, id: 'sign_out' do %>
            <i class="fa fa-sign-out fa-fw"></i>
            <%= t 'layouts.navbar.logout' %>
          <% end %>
        </li>
      </ul>
    </li>
  </ul>

<% end %>

FeedBunch-app/app/views/layouts/navbar/_xs_menu_button.html.erb
<button id="toggle-menu-collapse"
        type="button"
        class="navbar-toggle pull-left navbar-toggle-left"
        data-toggle="collapse"
        data-target=".navbar-collapse">
  <i class="fa fa-bars fa-lg"></i>
</button>

FeedBunch-app/app/views/layouts/navbar/_xs_sidebar_toggle_button.html.erb
<div class="btn-group pull-right show-hide-sidebar-buttons">

  <button type="button"
          id="toggle-sidebar-visible"
          class="navbar-toggle navbar-toggle-right"
          ng-click="toggle_sidebar_visible()"
          ng-show="sidebar_visible"
          ng-cloak>
    <i class="fa fa-rss fa-lg"></i>
    <small><i class="fa fa-chevron-right"></i></small>
  </button>

  <button type="button"
          id="toggle-sidebar-hidden"
          class="navbar-toggle navbar-toggle-right"
          ng-click="toggle_sidebar_visible()"
          ng-hide="sidebar_visible"
          ng-cloak>
    <small><i class="fa fa-chevron-left"></i></small>
    <i class="fa fa-folder-open fa-lg"></i>
  </button>
</div>