FeedBunch-app/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'
require 'sidekiq-cron'

Rails.application.routes.draw do

  # Custom dynamic error pages
  %w( 404 422 500 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

  devise_for :users, skip: [:sessions, :passwords, :registrations, :confirmations, :unlocks]

  # Customize login, logout etc routes instead of the Devise defaults.
  # See this[https://github.com/plataformatec/devise/wiki/How-To:-Change-the-default-sign_in-and-sign_out-routes].
  devise_scope :user do
    # sessions
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session,via: Devise.mappings[:user].sign_out_via

    # passwords
    get '/password/new' => 'devise/passwords#new', as: :new_user_password
    post '/password/new' => 'devise/passwords#create', as: :user_password
    get '/password/edit' => 'devise/passwords#edit', as: :edit_user_password
    put '/password/edit' => 'devise/passwords#update'

    # registrations
    get '/signup' => 'devise/registrations#new', as: :new_user_registration
    post '/signup' => 'feedbunch_auth/registrations#create', as: :user_registration
    get '/profile' => 'devise/registrations#edit', as: :edit_user_registration
    put '/profile' => 'devise/registrations#update'
    delete '/profile' => 'feedbunch_auth/registrations#destroy', as: :delete_user_registration

    # confirmations
    get '/resend_confirmation' => 'devise/confirmations#new', as: :new_user_confirmation
    post '/resend_confirmation' => 'devise/confirmations#create', as: :user_confirmation
    get '/confirmation' => 'devise/confirmations#show'

    # unlocks
    get '/unlock' => 'devise/unlocks#new', as: :new_user_unlock
    post '/unlock' => 'devise/unlocks#create', as: :user_unlock
    get '/unlock_account' => 'devise/unlocks#show'
  end

  # Redirect authenticated users that access the root URL to '/read'
  authenticated :user do
    get '/'  => redirect('/read')
  end

  # Static pages served with High_voltage gem
  root to: 'high_voltage/pages#show', id: 'index'
  get '/signup-success' => 'high_voltage/pages#show', id: 'signup-success', as: :signup_success

  # Main app page
  get '/read' => 'read#index', as: :read

  namespace :api do

    # Change entries state
    match '/entries/update' => 'entries#update', via: [:patch, :put], as: 'entries_update'

    # Resourceful routes for feeds
    resources :feeds, only: [:index, :show, :create, :update, :destroy] do
      resources :entries, only: [:index]
    end

    # Resourceful routes for folders
    resources :folders, only: [:index, :show, :update, :create] do
      resources :entries, only: [:index]
      resources :feeds, only: [:index]
    end

    # Resourceful routes for subscriptions import process state
    resource :opml_imports, only: [:show, :create, :update]

    # Resourceful routes for subscriptions export process state
    resource :opml_exports, only: [:show, :create, :update]

    # Download OPML export file
    match '/opml_exports/download' => 'opml_exports#download', via: [:get], as: 'opml_exports_download'

    # Resourceful routes for user config
    resource :user_config, only: [:show, :update]

    # Resourceful routes for user data
    resource :user_data, only: [:show]

    # Resourceful routes for refresh_feed_job_states
    resources :refresh_feed_job_states, only: [:index, :show, :destroy]

    # Resourceful routes for subscribe_job_states
    resources :subscribe_job_states, only: [:index, :show, :destroy]

    # Resourceful routes for application tours i18n strings.
    match '/tours/main' => 'tours#show_main', via: [:get], as: 'tours_show_main'
    match '/tours/mobile' => 'tours#show_mobile', via: [:get], as: 'tours_show_mobile'
    match '/tours/feed' => 'tours#show_feed', via: [:get], as: 'tours_show_feed'
    match '/tours/entry' => 'tours#show_entry', via: [:get], as: 'tours_show_entry'
    match '/tours/kb_shortcuts' => 'tours#show_kb_shortcuts', via: [:get], as: 'tours_show_kb_shortcuts'
  end

  # Restrict access to Sidekiq web ui to admin users only
  constraints CanAccessSidekiq do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Redmon is only accessible for admins
  constraints CanAccessRedmon do
    mount Redmon::App => '/redmon'
  end

  # ActiveAdmin is only accessible for admins
  constraints CanAccessActiveAdmin do
    # ActiveAdmin will be accessible in the /admin path
    ActiveAdmin.routes self
  end

  # PgHero is only accessible for admins
  constraints CanAccessPgHero do
    mount PgHero::Engine, at: 'pghero'
  end
end

FeedBunch-app/app/controllers/read_controller.rb
# frozen_string_literal: true

##
# Controller to access the main application page

class ReadController < ApplicationController

  before_action :authenticate_user!

  respond_to :html

  ##
  # return the main application page

  def index
    respond_with
  rescue => e
    handle_error e
  end

end

FeedBunch-app/app/views/read/job_states/_opml_export.html.erb
<% cache "opml_export-#{I18n.locale}" do %>

  <div id="export-process-state" class="row" ng-show="show_export_alert && export_state!='NONE'">

    <div class="col-xs-12 col-md-10 col-md-offset-2">

      <div class="row">
        <div class="col-xs-12 col-md-9 alert alert-danger" ng-show="export_state=='ERROR'">

          <button type="button"
                  class="close"
                  ng-click="hide_export_alert()"
                  title="<%= t 'read.job_states.dismiss' %>"
                  data-toggle="tooltip"
                  data-placement="top">
            &times;
          </button>

          <div class="row">
            <div class="col-xs-3 col-sm-2">
              <i class="fa fa-warning fa-4x"></i>
            </div>

            <div class="col-xs-9 col-sm-10">

              <p><%= t 'read.job_states.opml_export.error' %></p>
              <p>
                <%= link_to api_opml_exports_path(locale: I18n.locale),
                            :method => :post,
                            class: 'alert-link' do %>
                  <%= t 'read.job_states.opml_export.retry_error_1' %>
                <% end %>
                <%= t 'read.job_states.opml_export.retry_error_2' %>
              </p>
            </div>
          </div>

        </div>
      </div>

      <div class="row">
        <div id="opml-export-running" class="col-xs-12 col-md-9 alert alert-info" ng-show="export_state=='RUNNING'">

          <div class="row">
            <div class="col-xs-3 col-sm-2">
              <i class="fa fa-cog fa-spin fa-4x"></i>
            </div>

            <div class="col-xs-9 col-sm-10">

              <p><%= t 'read.job_states.opml_export.export_running' %></p>
              <p><%= t 'read.job_states.opml_export.export_background' %></p>

            </div>
          </div>

        </div>
      </div>


      <div class="row">
        <div class="col-xs-12 col-md-9 alert alert-success" ng-show="export_state=='SUCCESS'">

          <button type="button"
                  class="close"
                  ng-click="hide_export_alert()"
                  title="<%= t 'read.job_states.dismiss' %>"
                  data-toggle="tooltip"
                  data-placement="top">
            &times;
          </button>

          <div class="row">
            <div class="col-xs-3 col-sm-2">
              <i class="fa fa-share-square-o fa-4x"></i>
            </div>

            <div class="col-xs-9 col-sm-10">

              <p><%= t 'read.job_states.opml_export.success' %></p>
              <p>
                <%= link_to api_opml_exports_download_path,
                            class: 'alert-link',
                            id: 'download-opml-export' do %>
                  <%= t 'read.job_states.opml_export.download_success_1' %>
                <% end %>
                <%= t 'read.job_states.opml_export.download_success_2' %>
              </p>

            </div>
          </div>

        </div>
      </div>

    </div>
  </div>

<% end %>

FeedBunch-app/app/views/read/job_states/_opml_import.html.erb
<% cache "opml_import-#{I18n.locale}" do %>

  <div id="import-process-state" class="row" ng-show="show_import_alert">

    <div class="col-xs-12 col-md-10 col-md-offset-2">

      <div class="row">
        <div class="col-xs-12 col-md-9 alert alert-danger" ng-show="import_state=='ERROR'">

          <button type="button"
                  class="close"
                  ng-click="hide_import_alert()"
                  title="<%= t 'read.job_states.dismiss' %>"
                  data-toggle="tooltip"
                  data-placement="top">
            &times;
          </button>

          <div class="row">
            <div class="col-xs-3 col-sm-2">
              <i class="fa fa-warning fa-4x"></i>
            </div>

            <div class="col-xs-9 col-sm-10">

              <p><%= t 'read.job_states.opml_import.error' %></p>
              <p><a class="alert-link" data-toggle="modal" data-target="#opml-import-popup"><%= t 'read.job_states.opml_import.retry_error_1' %></a> <%= t 'read.job_states.opml_import.retry_error_2' %></p>

            </div>
          </div>

        </div>
      </div>

      <div class="row">
        <div id="opml-import-running" class="col-xs-12 col-md-9 alert alert-info" ng-show="import_state=='RUNNING'">

          <div class="row">
            <div class="col-xs-3 col-sm-2">
              <i class="fa fa-cogs fa-4x"></i>
            </div>

            <div class="col-xs-9 col-sm-10">

              <p><%= t 'read.job_states.opml_import.import_running' %></p>
              <p>
                <%= t 'read.job_states.opml_import.progress' %>
              </p>
              <div class="progress progress-striped active">
                <div class="progress-bar" style="width: {{100 * import_processed / import_total}}%;">
                  <span class="sr-only">{{100 * import_processed / import_total}}%</span>
                </div>
              </div>
              <p><%= t 'read.job_states.opml_import.import_background' %></p>

            </div>
          </div>

        </div>
      </div>


      <div class="row">
        <div class="col-xs-12 col-md-9 alert alert-success" ng-show="import_state=='SUCCESS'">

          <button type="button"
                  class="close"
                  ng-click="hide_import_alert()"
                  title="<%= t 'read.job_states.dismiss' %>"
                  data-toggle="tooltip"
                  data-placement="top">
            &times;
          </button>

          <div class="row">
            <div class="col-xs-3 col-sm-2">
              <i class="fa fa-thumbs-o-up fa-4x"></i>
            </div>

            <div class="col-xs-9 col-sm-10">

              <p><%= t 'read.job_states.opml_import.success' %></p>

              <p ng-show="import_failures.length > 0">
                <%= t 'read.job_states.opml_import.failures' %>
                <ul id="import-failures">
                  <li ng-repeat="failure in import_failures">{{failure}}</li>
                </ul>
              </p>

              <p>
                <a class="alert-link" data-toggle="modal" data-target="#opml-import-popup">
                  <%= t 'read.job_states.opml_import.retry_success_1' %>
                </a> <%= t 'read.job_states.opml_import.retry_success_2' %>
              </p>
            </div>
          </div>

        </div>
      </div>


      <div class="row">
        <div class="col-xs-12 col-md-9 alert alert-warning" ng-show="import_state=='NONE'">

          <button type="button"
                  class="close"
                  ng-click="hide_import_alert()"
                  title="<%= t 'read.job_states.dismiss' %>"
                  data-toggle="tooltip"
                  data-placement="top">
            &times;
          </button>

          <div class="row">
            <div class="col-xs-3 col-sm-2">
              <i class="fa fa-magic fa-4x"></i>
            </div>

            <div class="col-xs-9 col-sm-10">

              <p><%= t 'read.job_states.opml_import.introduction' %></p>
              <ol class="start-list icons-ul">
                <li>
                  <i class="fa fa-angle-right"></i>
                  <%= t 'read.job_states.opml_import.download_data_html' %>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a id="start-opml-import"
                     class="alert-link"
                     data-toggle="modal"
                     data-target="#opml-import-popup"><%= t 'read.job_states.opml_import.import_data_1' %></a><%= t 'read.job_states.opml_import.import_data_2' %>
                </li>
              </ol>

            </div>
          </div>

        </div>
      </div>

    </div>
  </div>

<% end %>

FeedBunch-app/app/views/read/job_states/_refresh_feed_job_states.html.erb
<% cache "refresh_feed_job_states-#{I18n.locale}" do %>

  <div id="refresh-state-alerts"
       class="row"
       ng-repeat="job_state in refresh_feed_job_states | orderBy:'-started_at'">

    <div id="refresh-state-{{job_state.id}}"
         ng-mouseenter="tooltips_refresh_job_state(job_state)">

      <div class="col-xs-12 col-md-9 alert alert-danger" ng-show="job_state.state=='ERROR'">

        <button type="button"
                class="close"
                ng-click="hide_refresh_job_alert(job_state)"
                title="<%= t 'read.job_states.dismiss' %>"
                data-toggle="tooltip"
                data-placement="top">
          &times;
        </button>

        <div class="row">
          <div class="col-xs-3 col-sm-2">
            <i class="fa fa-refresh fa-4x"></i>
          </div>

          <div class="col-xs-9 col-sm-10">
            <p><%= t 'read.job_states.refresh_feed.error' %></p>
            <p><a class="job-feed-title alert-link" ng-click="hide_refresh_job_alert(job_state);set_current_feed(job_state.feed_id)" ng-bind-html="feed_title(job_state.feed_id)"></a></p>
          </div>
        </div>

      </div>

      <div class="col-xs-12 col-md-9 alert alert-info" ng-show="job_state.state=='RUNNING'">

        <button type="button"
                class="close"
                ng-click="hide_refresh_job_alert(job_state)"
                title="<%= t 'read.job_states.dismiss' %>"
                data-toggle="tooltip"
                data-placement="top">
          &times;
        </button>

        <div class="row">
          <div class="col-xs-3 col-sm-2">
            <i class="fa fa-refresh fa-spin fa-4x"></i>
          </div>

          <div class="col-xs-9 col-sm-10">
            <p><%= t 'read.job_states.refresh_feed.running' %></p>
            <p><a class="job-feed-title alert-link" ng-click="hide_refresh_job_alert(job_state);set_current_feed(job_state.feed_id)" ng-bind-html="feed_title(job_state.feed_id)"></a></p>
          </div>
        </div>

      </div>

      <div class="col-xs-12 col-md-9 alert alert-success" ng-show="job_state.state=='SUCCESS'">

        <button type="button"
                class="close"
                ng-click="hide_refresh_job_alert(job_state)"
                title="<%= t 'read.job_states.dismiss' %>"
                data-toggle="tooltip"
                data-placement="top">
          &times;
        </button>

        <div class="row">
          <div class="col-xs-3 col-sm-2">
            <i class="fa fa-refresh fa-4x"></i>
          </div>

          <div class="col-xs-9 col-sm-10">
            <p><%= t 'read.job_states.refresh_feed.success' %></p>
            <p><a class="job-feed-title alert-link" ng-click="hide_refresh_job_alert(job_state);set_current_feed(job_state.feed_id)" ng-bind-html="feed_title(job_state.feed_id)"></a></p>
          </div>
        </div>

      </div>

    </div>

  </div>

<% end %>

FeedBunch-app/app/views/read/job_states/_subscribe_job_states.html.erb
<% cache "subscribe_job_states-#{I18n.locale}" do %>

  <div id="subscribe-state-alerts"
       class="row"
       ng-repeat="job_state in subscribe_job_states | orderBy:'-started_at'">

    <div id="subscribe-state-{{job_state.id}}"
         ng-mouseenter="tooltips_subscribe_job_state(job_state)">

      <div class="col-xs-12 col-md-9 alert alert-danger" ng-show="job_state.state=='ERROR'">

        <button type="button"
                class="close"
                ng-click="hide_subscribe_job_alert(job_state)"
                title="<%= t 'read.job_states.dismiss' %>"
                data-toggle="tooltip"
                data-placement="top">
          &times;
        </button>

        <div class="row">
          <div class="col-xs-3 col-sm-2">
            <i class="fa fa-plus fa-4x"></i>
          </div>

          <div class="col-xs-9 col-sm-10">
            <p><%= t 'read.job_states.subscribe.error' %></p>
            <p><span class="job-feed-title">{{job_state.fetch_url}}</span></p>
          </div>
        </div>

      </div>

      <div class="col-xs-12 col-md-9 alert alert-info" ng-show="job_state.state=='RUNNING'">

        <button type="button"
                class="close"
                ng-click="hide_subscribe_job_alert(job_state)"
                title="<%= t 'read.job_states.dismiss' %>"
                data-toggle="tooltip"
                data-placement="top">
          &times;
        </button>

        <div class="row">
          <div class="col-xs-3 col-sm-2">
            <i class="fa fa-cog fa-spin fa-4x"></i>
          </div>

          <div class="col-xs-9 col-sm-10">
            <p><%= t 'read.job_states.subscribe.running' %></p>
            <p><span class="job-feed-title">{{job_state.fetch_url}}</span></p>
          </div>
        </div>

      </div>

      <div class="col-xs-12 col-md-9 alert alert-success" ng-show="job_state.state=='SUCCESS'">

        <button type="button"
                class="close"
                ng-click="hide_subscribe_job_alert(job_state)"
                title="<%= t 'read.job_states.dismiss' %>"
                data-toggle="tooltip"
                data-placement="top">
          &times;
        </button>

        <div class="row">
          <div class="col-xs-3 col-sm-2">
            <i class="fa fa-plus fa-4x"></i>
          </div>

          <div class="col-xs-9 col-sm-10">
            <p><%= t 'read.job_states.subscribe.success' %></p>
            <p><a class="job-feed-title alert-link" ng-click="hide_subscribe_job_alert(job_state);set_current_feed(job_state.feed_id)" ng-bind-html="feed_title(job_state.feed_id)"></a></p>
          </div>
        </div>

      </div>

    </div>

  </div>

<% end %>